---
- name: "test connectivity"
  hosts: all
  pre_tasks:
    - name: Test | pre_tasks wait_for_connection
      ansible.builtin.ping:
    - name: Test | pre_tasks Shell on hosts
      shell: "uname -a ; echo {{ ansible_host }}"
  tags: always

- name: Set up k3s cluster
  hosts: all
  become: True
  pre_tasks:
    - name: init first control node
      when: '"master_init" in group_names'
      ansible.builtin.set_fact:
        K3S_CLUSTER_INIT: true

    - name: Set each node to be a control node
      when: '"master_add" in group_names'
      ansible.builtin.set_fact:
        K3S_SERVER: true

    - name: Set node to be agent node
      when: '"agent" in group_names'
      ansible.builtin.set_fact:
        K3S_AGENT: true

- name: Check facts
  hosts: all
  serial: '{{ serial | default("0") }}'
  pre_tasks:
    - name: K3S_CLUSTER_INIT
      debug: var=K3S_CLUSTER_INIT
      when: K3S_CLUSTER_INIT is defined and K3S_CLUSTER_INIT
    - name: K3S_SERVER
      debug: var=K3S_SERVER
      when: K3S_SERVER is defined and K3S_SERVER
    - name: K3S_AGENT
      debug: var=K3S_AGENT
      when: K3S_AGENT is defined and K3S_AGENT
    - debug: var=count_group_master
    - debug: var=count_env_master
    - debug: var=count_master
    - debug: var=k3s_url
    #- fail: msg=stop

  roles:
    - role: apt
    - role: docker
    - role: k3s
