---
- include_tasks: configure-proxy.yml
  when: proxy_env is defined and proxy_env.keys() | length > 0
 
- name: Configure apt.conf
  lineinfile:
    create: true
    dest: "{{ apt_conf_config_file }}"
    owner: root
    group: root
    mode: 0644
    regexp: '{{ item.key }}\s+.*'
    line: '{{ item.key }} {{ item.value }}'
    state: "{{ item.state | default('present') }}"
  with_items: "{{ apt_conf }}"
