---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  register: apt_res
  retries: 10
  delay: 5
  until: apt_res is success

- name: Ensure packages dependencies is installed
  apt:
    pkg: "{{ apt_default_packages }}"
    state: "present"
  register: apt_res
  retries: 10
  delay: 5
  until: apt_res is success
