---
- name: apt-get update
  apt:
    update_cache: yes
  register: apt_res
  retries: 10
  delay: 5
  until: apt_res is success

- name: Ensure packages dependencies is installed
  apt:
    pkg: "{{ apt_default_packages }}"
    state: "present"
  register: apt_res
  retries: 10
  delay: 5
  until: apt_res is success

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
