docker_install_compose_plugin: false
docker_install_compose: true

docker_compose_version_default: "v2.23.3"
docker_compose_version: "{{ lookup('ansible.builtin.env','docker_compose_version') | default(docker_compose_version_default, true) }}"

docker_version_default: "docker-ce=5:24.0.9-1~debian.12~bookworm"
docker_packages:
  - "{{ lookup('ansible.builtin.env','docker_version') | default(docker_version_default, true) }}"

docker_daemon_options:
  log-driver: "json-file"
  log-opts: { "max-size": "10m", "max-file": "3" }
  mtu: 1450
  exec-opts: ["native.cgroupdriver=systemd"]

docker_users:
  - root
  - outscale

k3s_version_default: v1.28.5+k3s1
k3s_version: "{{ lookup('ansible.builtin.env','K3S_VERSION') | default(k3s_version_default, true) }}"

proxy_env:
  http_proxy: '{{ lookup("ansible.builtin.env","http_proxy")| default(False) }}'
  https_proxy: '{{ lookup("ansible.builtin.env","https_proxy")| default(False) }}'
  no_proxy: '{{ lookup("ansible.builtin.env","no_proxy")| default(False) }}'
#proxy_env:
#  http_proxy: http://localhost:8888
#  https_proxy: http://localhost:8888
#  no_proxy: .mydomain.internal
