---
#
# configure
#
- name: Add service environment variables
  when: extra_service_envs is defined
  lineinfile:
    path: "{{ systemd_dir }}/{{ 'k3s-agent' if K3S_AGENT is defined else 'k3s' }}.service.env"
    line: "{{ item }}"
  with_items: "{{ extra_service_envs }}"

#- import_tasks: http_proxy.yml
#  when: proxy_env is defined and proxy_env.keys() | length > 0

- block:
  - name: Ensure that the manifests directory exists
    ansible.builtin.file:
      state: directory
      path: "{{ k3s_server_manifests_dir }}"
      mode: 0755
    when: k3s_server_manifests_templates | length > 0
    become: true

  - include_tasks: preconfigure-auto-deploying-manifests.yml
    loop: "{{ k3s_server_manifests_templates }}"
  when: ( K3S_CLUSTER_INIT is defined and K3S_CLUSTER_INIT )
          and k3s_server_manifests_templates | length > 0
