---
- name: Check k3s version.
  command: "{{ k3s_binary }} --version"
  register: k3s_version_detected
  check_mode: false
  changed_when: false
  failed_when: false

- set_fact:
    k3s_current_version: "{{ k3s_version_detected.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
    k3s_is_installed: true
  when: >
    k3s_version_detected.stdout is defined
    and (k3s_version_detected.stdout | length > 0)
