---
# https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests
- name: Set vars
  set_fact: "{{ local_var.key }}={{ local_var.value }}"
  loop: "{{ item.vars | dict2items }}"
  loop_control:
    loop_var: local_var

- name: Ensure Auto-Deploying Manifests are copied to controllers
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item.dest }}"
    mode: 0644
  become: true
