---
- name: Prepare systemd configuration
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  when: proxy_env is defined and proxy_env.keys() | length > 0

- name: configure http_proxy in docker
  blockinfile:
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    create: yes
    block: |
      [Service]
      {% if proxy_env.http_proxy is defined and proxy_env.http_proxy | length > 0 %}
      Environment="HTTP_PROXY={{ proxy_env.http_proxy }}"
      {% endif %}
      {% if proxy_env.https_proxy is defined and proxy_env.https_proxy | length > 0 %}
      Environment="HTTPS_PROXY={{ proxy_env.https_proxy }}"
      {% endif %}
      {% if proxy_env.no_proxy is defined and proxy_env.no_proxy | length > 0 %}
      Environment="NO_PROXY=127.0.0.1,localhost,{{ proxy_env.no_proxy }}"
      {% endif %}
  when: proxy_env is defined and proxy_env.keys() | length > 0 and ansible_check_mode == false
  register: docker_conf_update

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify: restart docker
  when: docker_conf_update
