apt_conf_config_file: /etc/apt/apt.conf.d/99apt-conf-ansible-managed
apt_conf:
  - comment: 'retry failed downloaded files the given number of times'
    key: APT::Acquire::Retries
    value: '"10";'
  - key: APT::Get::Assume-Yes
    value: '"true";'
  - comment: 'Wait dpkg lock timeout'
    key: DPkg::Lock::Timeout
    value: '"60";'
  - key: APT::Install-Recommends
    value: '"false";'
  - key: APT::Install-Suggests
    value: '"false";'

unnecessary_services:
  - apt-daily.timer
  - apt-daily.service
  - apt-daily-upgrade.timer
  - apt-daily-upgrade.service
  - unattended-upgrades
unnecessary_packages:
  - unattended-upgrades
apt_default_packages:
    - sudo
    - curl
    - jq
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - make
    - git
    - unzip
    - python3-pip
